## Basic Configuration
baseurl = "/"
languageCode = "en"

theme = "hyde-hyde"

## Site Settings
[params]
    author = "Matabit"
    title = "Matabit Blog"
    description = "Blog site for the Matabit CIT480 Senior design team"
    authorimage = "/img/hugo.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"

## Main Menu
[[menu.main]]
    name = "Home"
    weight = 200
    url = "/"
[[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
