version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: /hugo
    environment:
      HUGO_BUILD_DIR: /hugo/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
  test:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: /hugo
    environment:
      HUGO_BUILD_DIR: /hugo/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: ls -la $HUGO_BUILD_DIR
      - run:
          name: "Test for HTML files"
          command: |
            htmlproofer $HUGO_BUILD_DIR    
  deploy-staging:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: /hugo
    environment:
      HUGO_BUILD_DIR: /hugo/public
    steps:
      - run: 
          name: Install aws cli and dependencies
          command : |
            apk update && apk add git python python-dev py-pip build-base
            pip install awscli
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: ls -la $HUGO_BUILD_DIR
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "circle-ci" ]; then
              tar -zcvf /hugo/${CIRCLE_SHA1}.tar.gz -C $HUGO_BUILD_DIR .
              aws s3 cp /hugo/${CIRCLE_SHA1}.tar.gz \
              $STAGING_BUCKET${CIRCLE_SHA1}.tar.gz
            else
              echo "Not master branch, dry run only"
            fi
  deploy-master:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: /hugo
    environment:
      HUGO_BUILD_DIR: /hugo/public
    steps:
      - run: 
          name: Install aws cli and dependencies
          command : |
            apk update && apk add git python python-dev py-pip build-base
            pip install awscli
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: ls -la $HUGO_BUILD_DIR
      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "circle-ci" ]; then
              tar -zcvf /hugo/${CIRCLE_SHA1}.tar.gz -C $HUGO_BUILD_DIR .
              aws s3 cp /hugo/${CIRCLE_SHA1}.tar.gz \
              $MASTER_BUCKET${CIRCLE_SHA1}.tar.gz
            else
              echo "Not master branch, dry run only"
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
          - build
      - deploy-staging:
          requires:
            - test 
      - hold-production:
          type: approval
          requires:
            - test
      - deploy-master:
          requires:
            - hold-production