version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: /hugo
    environment:
      HUGO_BUILD_DIR: /hugo/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
  test:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: /hugo
    environment:
      HUGO_BUILD_DIR: /hugo/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: ls -la $HUGO_BUILD_DIR
      - run:
          name: "Test for HTML files"
          command: |
            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
