version: 2
jobs:
  build-test:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: /hugo
    environment:
      HUGO_BUILD_DIR: /hugo/public
    steps:
      - run: apk update && apk add git
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: ls -la $HUGO_BUILD_DIR
      - run:
          name: "Test for HTML files"
          command: |
            htmlproofer $HUGO_BUILD_DIR    
  deploy-staging:
    docker:
      - image: ssalehian/circleci-aws-docker:latest
    working_directory: /hugo
    environment:
      HUGO_BUILD_DIR: /hugo/public
      BUILD_ENV: staging
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: ls -la $HUGO_BUILD_DIR
            

  deploy-master:
    docker:
      - image: ssalehian/circleci-aws-docker:latest
    working_directory: /hugo
    environment:
      HUGO_BUILD_DIR: /hugo/public
      BUILD_ENV: prod
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: ls -la $HUGO_BUILD_DIR


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build-test
      - deploy-staging:
          requires:
            - build-test 
      - hold-master:
          type: approval
          requires:
            - build-test
      - deploy-master:
          requires:
            - hold-master